### ISSUE TITLE
Clicking save sometimes add another entry.

### ISSUE THREAD

**Issue by ArabCoders** [jellyfin/jellyfin-plugin-webhook#113]
Version: 10.7.7
Operating System: Linux
Architecture: X64
Webhook: 8.0.0.0

Sometimes when you click save button fast multiple times, the record get duplicated instead of being updated.

**Comment by crobibero** [comment]
Then don't do that

**Comment by ArabCoders** [comment]
@crobibero  Do you think i intentionally want to do that? some times it triggers randomly, i had to remove all the added webhook destinations to get this thing working again.

**Comment by TimGels** [comment]
Why is this closed? I think (with my limited web client and plugin knowledge, so please correct me if I am wrong) the issue is valid. One would think that this is unwanted behavior and thus deserves to be on the issue tracker. Even if its really low priority, just to have it known. What could be the cause of this? The web client implementation as in how that works internally?

**Comment by crobibero** [comment]
I cannot reproduce the issue

**Comment by ArabCoders** [comment]
> I cannot reproduce the issue

from my testing this is how im able to reproduce it, 

1. visit the plugin page, add a webhook.
2. go back to home or any other page. then go back to plugin page, click save and use the the browser back button and then forward back again to plugin page, you will see two entries.

**Comment by crobibero** [comment]
Reproduced from video explaining how.
As mentioned in chat, unsure if this is a web or plugin bug

**Comment by ArabCoders** [comment]
video example of the bug, posted as requested in discord.

https://user-images.githubusercontent.com/1621552/163839644-0e79738f-3dbf-4667-a6e5-3729f1570f90.mp4
