### ISSUE TITLE
Jellyfin log is flooded with messages "Webhook Item Added Notifier" & "Webhook Item Deleted Notifier"

### ISSUE THREAD

**Issue by fa1rid** [jellyfin/jellyfin-plugin-webhook#300]
The similar old issue is still there [issue #10](https://github.com/jellyfin/jellyfin-plugin-webhook/issues/10).

After installing the plugin, the log is flooded with distracting unnecessary messages:

```
[INF] [19] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 
[INF] [19] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Deleted Notifier" Completed after 0 minute(s) and 0 seconds
```

Can someone please look into it?

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin-plugin-webhook/issues/10#issuecomment-776089378

**Comment by fa1rid** [comment]
Instead of closing the issue silently, could you please clarify how can we help to fix this issue, and what is the cause of it?

**Comment by fa1rid** [comment]
Also, I only have `Item Added` webhook enabled. I don't have any `Item Deleted`, why `Item Deleted` is showing it in the logs?

**Comment by fa1rid** [comment]
I assume from the log and the interval between these messages, that there is a scheduled task running every 1.5 mins, that checks if any item was added or deleted from the library, right? Is this related to the webhook plugin or Jellyfin sever itself?

A briefing of what's going on would be appreciated.

**Comment by crobibero** [comment]
Yes, there is a scheduled task running. The tasks are always enabled unless the server admin disables them.
There is nothing to fix in this repo, and the linked comment has the same response which is why I linked it.

https://github.com/jellyfin/jellyfin-plugin-webhook/blob/master/Jellyfin.Plugin.Webhook/Notifiers/ItemAddedNotifier/ItemAddedScheduledTask.cs
https://github.com/jellyfin/jellyfin-plugin-webhook/blob/master/Jellyfin.Plugin.Webhook/Notifiers/ItemDeletedNotifier/ItemDeletedScheduledTask.cs
