### ISSUE TITLE
Pause / Play webhook

### ISSUE THREAD

**Issue by grambas** [jellyfin/jellyfin-plugin-webhook#99]
What do you think about adding pause and play webhook types? It could be used for home automation for example to turn on or turn of cinema mode

**Comment by crobibero** [comment]
These is already PlaybackStart and PlaybackStop, do these not do what you need?

**Comment by grambas** [comment]
PlaybackStart is fired once when I start to play movie. Pause and Resume actions does not trigger PlaybackStart PlaybackStop hooks

**Comment by crobibero** [comment]
This is how Jellyfin sends the events:

- `PlaybackStart` is when the user begins playback
- `PlaybackProgress` is the user's playing state
	- `IsPaused` is whether the playback is paused or not
- `PlaybackStop` is when the user ends playback

**Comment by Bandit** [comment]
`PlaybackProgress` absolutely hammers the endpoint. You can't use a conditional based on `IsAutomated` either since that always seems to be `false`.

Why is there no way to simply know if a user has paused or resumed the media? This is another vote for a Pause endpoint which essentially just checks if the `IsPaused` variable has changed from its previous state, and if so, send the event.

**Comment by rodrigocabraln** [comment]
> `PlaybackProgress` absolutely hammers the endpoint. You can't use a conditional based on `IsAutomated` either since that always seems to be `false`.
> 
> Why is there no way to simply know if a user has paused or resumed the media? This is another vote for a Pause event type which essentially just checks if the `IsPaused` variable has changed from its previous state, and if so, send the event.

Hi, Try this thing i made, it works well for me.

https://github.com/rodrigocabraln/JellyHookDebouncer
